# Generated by Django 2.2.7 on 2019-12-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField()),
                ('start', models.CharField(max_length=120)),
                ('finish', models.CharField(max_length=120)),
                ('distance', models.CharField(max_length=50)),
                ('base_stake', models.IntegerField()),
                ('winner', models.CharField(max_length=120)),
            ],
        ),
    ]
