# Generated by Django 2.2.7 on 2019-12-08 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Past_Races',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_date', models.DateTimeField()),
                ('start', models.CharField(max_length=120)),
                ('finish', models.CharField(max_length=120)),
                ('distance', models.CharField(max_length=50)),
                ('base_stake', models.IntegerField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Races',
            new_name='Future_Races',
        ),
    ]
