# Generated by Django 2.2.7 on 2019-12-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20191208_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='future_races',
            name='winner',
        ),
        migrations.AddField(
            model_name='past_races',
            name='winner',
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
    ]
