# Generated by Django 2.2.7 on 2019-12-08 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_auto_20191208_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='future_races',
            name='base_stake',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='future_races',
            name='distance',
            field=models.FloatField(max_length=50),
        ),
        migrations.AlterField(
            model_name='past_races',
            name='base_stake',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='past_races',
            name='distance',
            field=models.FloatField(max_length=50),
        ),
    ]
