# Generated by Django 2.2.7 on 2019-12-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_auto_20191209_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stakes',
            name='name',
            field=models.CharField(choices=[('Marko', 'Marko Karpats'), ('Igor', 'Igor Bobkin')], max_length=50),
        ),
    ]
