# Generated by Django 2.2.7 on 2019-12-05 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drivers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('about', models.TextField()),
                ('races_participated', models.IntegerField()),
                ('races_won', models.IntegerField()),
                ('driving_exp', models.IntegerField()),
                ('date_of_getting_driving_licens', models.DateTimeField()),
                ('reg_date', models.DateTimeField()),
            ],
        ),
    ]
