# Generated by Django 2.2.7 on 2019-12-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivers',
            name='driving_exp',
        ),
        migrations.AddField(
            model_name='drivers',
            name='profile_pic',
            field=models.CharField(default='https://icon-library.net/images/profile-icon-white/profile-icon-white-3.jpg', max_length=250),
        ),
        migrations.AddField(
            model_name='drivers',
            name='status',
            field=models.CharField(default=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='date_of_getting_driving_licens',
            field=models.DateField(),
        ),
    ]
