# Generated by Django 2.2.7 on 2019-12-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_auto_20191208_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='status',
            field=models.CharField(choices=[('True', 'True'), ('False', 'False')], default=False, max_length=10),
        ),
    ]
