# Generated by Django 3.0 on 2019-12-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0002_auto_20191209_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='account_profile',
            name='profile_pic',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
