# Generated by Django 3.0 on 2019-12-08 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0003_account_profile_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account_profile',
            old_name='profile_pic',
            new_name='account_pic',
        ),
    ]
