# Generated by Django 2.2.7 on 2019-12-11 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0005_auto_20191209_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_profile',
            name='driving_licens',
        ),
    ]
