# Generated by Django 2.2.7 on 2019-12-11 13:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0008_account_profile_account_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='account_create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 13, 29, 48, 15656, tzinfo=utc)),
        ),
    ]
