# Generated by Django 2.2.7 on 2019-12-11 13:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0010_auto_20191211_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account_profile',
            name='account_create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 13, 42, 19, 219858, tzinfo=utc)),
        ),
    ]
