# Generated by Django 2.2.7 on 2019-12-11 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account_profile', '0012_auto_20191211_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account_profile',
            name='account_status',
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='account_create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 11, 14, 22, 41, 518054, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='account_pic',
            field=models.CharField(default='../main/profile_icon.png', max_length=250),
        ),
    ]
